# Generated by Django 5.0.7 on 2024-11-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
