# Generated by Django 5.0.7 on 2024-12-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_product_category_product_color_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_description',
            field=models.CharField(max_length=255),
        ),
    ]
