# Generated by Django 5.0.7 on 2024-12-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_product_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
