# Generated by Django 5.0.7 on 2024-12-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_order_orderitem_transaction_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
    ]
