# Generated by Django 5.0.7 on 2024-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
