# Generated by Django 5.0.7 on 2024-12-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_contact_is_read_contact_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/placeholder.png', upload_to='profile_images/'),
        ),
    ]
